
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nguyen Hai Dang
 */
public final class AddEquipmentDetailsForm extends javax.swing.JFrame {

    @Override
    public javax.swing.JFrame getParent() {
        return _parent;
    }

    public static AddEquipmentDetailsForm getObj(javax.swing.JFrame parent, int index, boolean isUpdate) {
        if (_obj == null) {
            _obj = new AddEquipmentDetailsForm(parent, index, isUpdate);
        }
        return _obj;
    }

    /**
     * Creates new form AddEquimentForm
     *
     * @param parent
     */
    public AddEquipmentDetailsForm(javax.swing.JFrame parent, int index, boolean isUpdate) {
        initComponents();
        this.setTitle("Thêm chi tiết thiết bị");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);

        _eC = new EquipmentDetailsController();
        _sC = new SupplierController();
        _listOfSuppliers = new ArrayList<>();
        _listOfEquipmentDetails = _eC.getListEquipmentDetails();
        _parent = parent;
        _isUpdate = isUpdate;

        getSupplierList();
        initAlert();

        if (isUpdate && index >= 0) {
            fillOutInfo(index);
        } else {
            btnConfirm.setText("Thêm");
            btnGetImage.setText("Chọn hình ảnh!");
        }

        closingWindow();
    }

    public void closingWindow() {
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                dispose();
                clearScreen();
            }
        });
    }

    public void clearScreen() {
        AddEquipmentDetailsForm._obj = null;
    }

    public void fillOutInfo(int index) {
        Equipment_Details eD = _listOfEquipmentDetails.get(index);
        int dem = 0;
        for (Supplier s : _listOfSuppliers) {
            if (s.getSupplierId() == eD.getSupplier_id()) {
                cbNhaCungCap.setSelectedIndex(dem);
                break;
            }
            dem++;
        }

        txtMaChiTietTB.setText(eD.getId());
        txtMaChiTietTB.setEditable(false);
        txtMaChiTietTB.setFocusable(false);
        txtTenThietBi.setText(eD.getName());
        txtTenThietBi.requestFocus();

        if (eD.getPicture() != null) {
            btnGetImage.setText(eD.getPicture());
            oldPicutre = eD.getPicture();
        } else {
            btnGetImage.setText("Chọn hình ảnh!");
        }

        txtGia.setText(eD.getPrice() + "");
        txtThoiGianBH.setText(eD.getWarranty_time() + "");
        btnConfirm.setText("Cập nhật");
    }

    public void initAlert() {
        initAlertLabel(alertMCTTB);
        initAlertLabel(alertTTB);
        initAlertLabel(alertGia);
        initAlertLabel(alertNCC);
        initAlertLabel(alertTGBH);
    }

    public void initAlertLabel(JLabel label) {
        label.setText("");
        label.setSize(0, 0);
    }

    public void getSupplierList() {
        cbNhaCungCap.removeAllItems();
        _listOfSuppliers = _sC.getSuppliersInfo();
        _listOfSuppliers.forEach((supplier) -> {
            cbNhaCungCap.addItem("Tên: " + supplier.getName() + ", Địa chỉ: " + supplier.getAddress());
        });
        cbNhaCungCap.addItem("Thêm nhà cung cấp");
    }

    public void resetField() {
        txtMaChiTietTB.setText("");
        txtTenThietBi.setText("");
        btnGetImage.setText("Chọn hình ảnh!");
        txtGia.setText("");
        txtThoiGianBH.setText("");
        cbNhaCungCap.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaChiTietTB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenThietBi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtThoiGianBH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbNhaCungCap = new javax.swing.JComboBox<>();
        btnGetImage = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        alertMCTTB = new javax.swing.JLabel();
        alertTTB = new javax.swing.JLabel();
        alertNCC = new javax.swing.JLabel();
        alertGia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        alertTGBH = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Mã chi tiết thiết bị :");

        txtMaChiTietTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaChiTietTBKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Tên thiết bị :");

        txtTenThietBi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenThietBiKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nhà cung cấp :");
        jLabel5.setToolTipText("");

        txtGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiaKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Giá :");

        btnConfirm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btnConfirm.setText("Cập nhật");
        btnConfirm.setToolTipText("");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.png"))); // NOI18N
        jButton2.setText("Hủy bỏ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Thời gian bảo hành:");

        txtThoiGianBH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtThoiGianBHKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Hình ảnh:");

        cbNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhaCungCapActionPerformed(evt);
            }
        });

        btnGetImage.setText("Chọn hình ảnh!");
        btnGetImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetImageActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        jButton3.setText("Làm mới");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        alertMCTTB.setForeground(new java.awt.Color(255, 0, 0));
        alertMCTTB.setLabelFor(txtMaChiTietTB);
        alertMCTTB.setText("Mã CTBB alert");

        alertTTB.setForeground(new java.awt.Color(255, 0, 0));
        alertTTB.setText("Tên TB alert");

        alertNCC.setForeground(new java.awt.Color(255, 0, 0));
        alertNCC.setText("NCC alert");

        alertGia.setForeground(new java.awt.Color(255, 0, 0));
        alertGia.setText("Giá TB alert");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("THÊM CHI TIẾT THIẾT BỊ");

        alertTGBH.setForeground(new java.awt.Color(255, 0, 0));
        alertTGBH.setText("TGBH alert");

        jLabel3.setText("VND");

        jLabel7.setText("năm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(alertMCTTB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(86, 86, 86)
                        .addComponent(txtTenThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(alertTTB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(alertNCC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(35, 35, 35)
                        .addComponent(txtThoiGianBH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtMaChiTietTB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(71, 71, 71)
                                .addComponent(cbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addGap(106, 106, 106)
                        .addComponent(btnGetImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(alertTGBH))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alertGia)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtMaChiTietTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertMCTTB, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTenThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertTTB, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGetImage)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertGia, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThoiGianBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertTGBH, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        initAlert();
        String maChiTietTB = txtMaChiTietTB.getText();
        String tenThietbi = txtTenThietBi.getText();
        String hinhAnh;

        if (_isUpdate) {
            System.out.println("update");
            if (btnGetImage.getText().equals("Chọn hình ảnh!")) {
                hinhAnh = null;
            } else if (btnGetImage.getText().contains("/")) {
                hinhAnh = btnGetImage.getText();
            } else {
                hinhAnh = "/src/images/" + btnGetImage.getText();
            }
        } else {
            System.out.println("add");
            if (btnGetImage.getText().equals("Chọn hình ảnh!")) {
                System.out.println("chọn hình ảnh");
                hinhAnh = null;
            } else {
                hinhAnh = "/src/images/" + btnGetImage.getText();
            }
        }

        String gia = txtGia.getText();
        String thoigianBH = txtThoiGianBH.getText();
        int selectedNhaCungCap = cbNhaCungCap.getSelectedIndex();
        int nhaCungCapId = 0;

        boolean check = true;

        if (maChiTietTB.length() == 0) {
            createAlert(alertMCTTB, "Mã CTTB không được để trống");
            check = false;
        }
        if (tenThietbi.length() == 0) {
            createAlert(alertTTB, "Tên thiết bị không được để trống");
            check = false;
        }
        if (gia.length() == 0) {
            createAlert(alertGia, "Giá TB không được để trống");
            check = false;
        }

        if (!maChiTietTB.matches("^[a-zA-Z]{3}[\\d]{2}$")) {
            createAlert(alertMCTTB, "Mã CTTB phải đúng định dạng 3 ký tự chữ và 2 ký tự số");
            check = false;
        }
        if (tenThietbi.length() > 0 && tenThietbi.matches("[^a-zA-Z]+")) {
            createAlert(alertTTB, "Tên TB không để trống và phải là ký tự chữ");
            check = false;
        }
        if (!gia.matches("\\d+") || Integer.parseInt(gia) < 10000) {
            createAlert(alertGia, "Giá TB ít nhất là 10000 và là ký tự số");
            check = false;
        }
        if (cbNhaCungCap.getSelectedItem().toString().equals("Thêm nhà cung cấp")) {
            createAlert(alertNCC, "Chọn 1 nhà cung cấp");
            check = false;
        }

        if (maChiTietTB.length() > 5) {
            createAlert(alertMCTTB, "Mã CTTB không được vượt quá 5 ký tự");
            check = false;
        }

        if (!thoigianBH.matches("[\\d]{1,2}")) {
            createAlert(alertTGBH, "Vui lòng nhập năm từ 0 đến 10");
            check = false;
        } else if (Integer.parseInt(thoigianBH) > 10 || Integer.parseInt(thoigianBH) < 0) {
            createAlert(alertTGBH, "Vui lòng nhập năm từ 0 đến 10");
            check = false;
        }

        if (check) {
            nhaCungCapId = _listOfSuppliers.get(selectedNhaCungCap).getSupplierId();
            int price = Integer.parseInt(gia);
            Equipment_Details eD = new Equipment_Details();
            eD.setId(maChiTietTB);
            eD.setName(tenThietbi);
            eD.setPicture(hinhAnh);
            eD.setPrice(price);
            eD.setSupplier_id(nhaCungCapId);
            if (thoigianBH.length() > 0) {
                eD.setWarranty_time(Integer.parseInt(thoigianBH));
            }

            if (_eC.isIdExist(maChiTietTB)) {
                if (_eC.updateEquipmentDetails(eD)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    try {
                        if (hinhAnh != null) {
                            _addImgFrame.saveImage();
                        }
                    } catch (NullPointerException e) {
                        System.out.println("Waiting");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất  bại");
                }
            } else {
                if (_eC.addNewEquipmentDetails(eD)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    if (hinhAnh != null) {
                        _addImgFrame.saveImage();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất  bại");
                }
            }

            if (_parent.getClass().getName().equals("MainMenu")) {
                MainMenu mainMenu = (MainMenu) _parent;
                mainMenu.loadDatabase();
            } else if (_parent.getClass().getName().equals("AddEquipmentForm")) {
                AddEquipmentForm addEquipment = (AddEquipmentForm) _parent;
                addEquipment.loadDetailIDComboBox(maChiTietTB);
            }

            clearScreen();
            resetField();
            this.dispose();
        }

    }//GEN-LAST:event_btnConfirmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        resetField();
        this.dispose();
        clearScreen();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGetImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetImageActionPerformed
        _addImgFrame = AddImage.getObj(btnGetImage, "Thêm hình ảnh thiết bị");
        _addImgFrame.setVisible(true);
    }//GEN-LAST:event_btnGetImageActionPerformed

    private void cbNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNhaCungCapActionPerformed
        int selectedItem = cbNhaCungCap.getSelectedIndex();

        if (selectedItem == _listOfSuppliers.size()) {
            cbNhaCungCap.hidePopup();
            new AddSupplierForm(this, -1, false, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_cbNhaCungCapActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        resetField();
        initAlert();
        if (_listOfSuppliers.size() != _sC.getSuppliersInfo().size()) {
            this.getSupplierList();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtMaChiTietTBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaChiTietTBKeyReleased
        String maCTTB = txtMaChiTietTB.getText();

        if (maCTTB.matches("^[a-zA-Z]{3}[\\d]{2}$") && txtMaChiTietTB.getText().length() > 0) {
            initAlertLabel(alertMCTTB);
        }
    }//GEN-LAST:event_txtMaChiTietTBKeyReleased

    private void txtTenThietBiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenThietBiKeyReleased
        String tenTB = txtTenThietBi.getText();

        if (tenTB.matches("^[a-zA-Z]+$") && tenTB.length() > 0) {
            initAlertLabel(alertTTB);
        }
    }//GEN-LAST:event_txtTenThietBiKeyReleased

    private void txtGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaKeyReleased
        String gia = txtGia.getText();
        if (gia.matches("^[\\d]+$") && Integer.parseInt(gia) >= 10000) {
            initAlertLabel(alertGia);
        }
    }//GEN-LAST:event_txtGiaKeyReleased

    private void txtThoiGianBHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThoiGianBHKeyReleased
        String thoigianBH = txtThoiGianBH.getText();
        if (thoigianBH.matches("^[\\d]{1,2}$")) {
            if (Integer.parseInt(thoigianBH) <= 10 && Integer.parseInt(thoigianBH) >= 1) {
                initAlertLabel(alertTGBH);
            }
        }
    }//GEN-LAST:event_txtThoiGianBHKeyReleased

    private void createAlert(JLabel label, String alertContent) {
        label.setSize(alertContent.length(), 17);
        label.setText(alertContent);
        label.setVisible(true);
    }

    private EquipmentDetailsController _eC = null;
    private SupplierController _sC = null;
    private List<Supplier> _listOfSuppliers;
    private List<Equipment_Details> _listOfEquipmentDetails;
    private javax.swing.JFrame _parent;
    private boolean _isUpdate;
    private AddImage _addImgFrame;
    private static AddEquipmentDetailsForm _obj = null;
    private String oldPicutre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertGia;
    private javax.swing.JLabel alertMCTTB;
    private javax.swing.JLabel alertNCC;
    private javax.swing.JLabel alertTGBH;
    private javax.swing.JLabel alertTTB;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnGetImage;
    private javax.swing.JComboBox<String> cbNhaCungCap;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaChiTietTB;
    private javax.swing.JTextField txtTenThietBi;
    private javax.swing.JTextField txtThoiGianBH;
    // End of variables declaration//GEN-END:variables
}
