
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import javax.swing.filechooser.FileFilter;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nguyen Hai Dang
 */
public class AddEquimentDetailsForm extends javax.swing.JFrame {
    
    EquipmentDetailsController eC = null;
    SupplierController sC = null;
    List<Supplier> listOfSuppliers;
    String imagePath;
    int size;
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    
    public String getImagePath() {
        return imagePath;
    }

    /**
     * Creates new form AddEquimentForm
     */
    public AddEquimentDetailsForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        eC = new EquipmentDetailsController();
        sC = new SupplierController();
        listOfSuppliers = new ArrayList<>();
        
        getSupplierList();
    }
    
    public void getSupplierList() {
        cbNhaCungCap.removeAllItems();
        listOfSuppliers = sC.getSuppliersInfo();
        for (Supplier supplier : listOfSuppliers) {
            cbNhaCungCap.addItem("Tên: " + supplier.getName() + ", Địa chỉ: " + supplier.getAddress());
        }
        cbNhaCungCap.addItem("Thêm nhà cung cấp");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaChiTietTB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenThietBi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtThoiGianBH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbNhaCungCap = new javax.swing.JComboBox<>();
        btnGetImage = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã chi tiết thiết bị :");

        jLabel4.setText("Tên thiết bị :");

        jLabel5.setText("Nhà cung cấp :");
        jLabel5.setToolTipText("");

        jLabel6.setText("Giá :");

        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Thời gian bảo hành:");

        jLabel9.setText("Hình ảnh:");

        cbNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhaCungCapActionPerformed(evt);
            }
        });

        btnGetImage.setText("Click to choose image");
        btnGetImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetImageActionPerformed(evt);
            }
        });

        jButton3.setText("Làm mới");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGetImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTenThietBi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(txtMaChiTietTB, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtGia, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(144, 144, 144))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtThoiGianBH)
                                        .addGap(45, 45, 45))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(34, 34, 34)
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaChiTietTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnGetImage))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtThoiGianBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String maChiTietTB = txtMaChiTietTB.getText();
        String tenThietbi = txtTenThietBi.getText();
        String hinhAnh = getImagePath();
        String gia = txtGia.getText();
        int selectedNhaCungCap = cbNhaCungCap.getSelectedIndex();
        String thoigianBH = txtThoiGianBH.getText();
        int nhaCungCapId = 0;
        
        boolean isSatisfied = true;
        
        if (maChiTietTB.length() == 0) {
            JOptionPane.showMessageDialog(this, "Mã chi tiết thiết bị không được để trống!");
            isSatisfied = false;
        } else if (tenThietbi.length() == 0) {
            JOptionPane.showMessageDialog(this, "Tên thiết bị không được để trống!");
            isSatisfied = false;
        } else if (gia.length() == 0) {
            JOptionPane.showMessageDialog(this, "Giá thiết bị không được để trống!");
            isSatisfied = false;
        } else if (thoigianBH.length() == 0) {
            JOptionPane.showMessageDialog(this, "Thời gian bảo hành không được để trống!");
            isSatisfied = false;
        }
        
        if (maChiTietTB.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Mã chi tiết thiết bị phải là kí tự ");
            isSatisfied = false;
        } else if (tenThietbi.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Tên thiết bị phải là chữ cái ");
            isSatisfied = false;
        } else if (gia.matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Gía thiết bị phải là chữ số ");
            isSatisfied = false;
        } else if (cbNhaCungCap.getSelectedItem().toString().equals("Thêm nhà cung cấp")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung cấp ");
            isSatisfied = false;
        }
        
        if (maChiTietTB.length() > 5) {
            JOptionPane.showMessageDialog(this, "Mã chi tiết thiết bị không được vượt quá 5 ký tự");
            isSatisfied = false;
        } else if (thoigianBH.length() > 2) {
            JOptionPane.showMessageDialog(this, "Thời gian bảo hành không được vượt quá 10 năm");
            isSatisfied = false;
        }
        
        if (isSatisfied) {
            nhaCungCapId = listOfSuppliers.get(selectedNhaCungCap).getSupplierId();
            int price = Integer.parseInt(gia);
            Equipment_Details eD = new Equipment_Details();
            eD.setId(maChiTietTB);
            eD.setName(tenThietbi);
            eD.setPicture(hinhAnh);
            eD.setPrice(price);
            eD.setSupplier_id(nhaCungCapId);
//                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//                eD.setWarranty_time(sdf.parse(txtThoiGianBH.getText()));
            eD.setWarranty_time(thoigianBH);
            
            if (eC.isIdExist(maChiTietTB)) {
                int option = JOptionPane.showConfirmDialog(this, "Mã chi tiết thiết bị đã tồn tại, bạn có muốn cập nhật thông tin không?");
                if (option == 0) {
                    if (eC.updateEquipmentDetails(eD)) {
                        JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                        txtMaChiTietTB.setText("");
                        txtTenThietBi.setText("");
                        btnGetImage.setText("Nhấn để chọn hình ảnh!");
                        txtGia.setText("");
                        cbNhaCungCap.setSelectedIndex(0);
                        txtThoiGianBH.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, "Cập nhật thất  bại");
                    }
                }
            } else {
                if (eC.addNewEquipmentDetails(eD)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    txtMaChiTietTB.setText("");
                    txtTenThietBi.setText("");
                    btnGetImage.setText("Nhấn để chọn hình ảnh!");
                    txtGia.setText("");
                    cbNhaCungCap.setSelectedIndex(0);
                    txtThoiGianBH.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất  bại");
                }
            }
            
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGetImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetImageActionPerformed
        createWindow();
    }//GEN-LAST:event_btnGetImageActionPerformed

    private void cbNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNhaCungCapActionPerformed
        int selectedItem = cbNhaCungCap.getSelectedIndex();
        
        if (selectedItem == listOfSuppliers.size()) {
            cbNhaCungCap.hidePopup();
            new AddSupplier(this, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_cbNhaCungCapActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtMaChiTietTB.setText("");
        txtTenThietBi.setText("");
        btnGetImage.setText("Nhấn để chọn hình ảnh!");
        txtGia.setText("");
        txtThoiGianBH.setText("");
        cbNhaCungCap.setSelectedIndex(0);
        if (listOfSuppliers.size() != sC.getSuppliersInfo().size()) {
            this.getSupplierList();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void createWindow() {
        JFrame frame = new JFrame("Choose Image");
        frame.setLayout(null);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(700, 460);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        createUI(frame);
    }
    
    public void createUI(final JFrame frame) {
        JButton browseButton = new JButton("Browse");
        browseButton.setBounds(300, 380, 100, 40);
        JLabel labelImage = new JLabel();
        labelImage.setBounds(10, 10, 670, 250);
        JLabel labelText = new JLabel();
        labelText.setBounds(10, 300, 670, 60);
        
        frame.add(browseButton);
        frame.add(labelImage);
        frame.add(labelText);
        
        browseButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
                fileChooser.addChoosableFileFilter(new ImageFilter());
                fileChooser.setAcceptAllFileFilterUsed(false);
                
                int result = fileChooser.showSaveDialog(null);
                if (result == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    String path = selectedFile.getAbsolutePath();
                    labelImage.setIcon(ResizeImage(path, labelImage));
                    labelText.setText("File name: " + selectedFile.getName());
                    setImagePath(path);
                    btnGetImage.setText(selectedFile.getName());
                    
                } else if (result == JFileChooser.CANCEL_OPTION) {
                    System.out.println("\"No File Selected\"");
                }
            }
        });
    }
    
    static public ImageIcon ResizeImage(String imagePath, JLabel label) {
        ImageIcon myImage = new ImageIcon(imagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetImage;
    private javax.swing.JComboBox<String> cbNhaCungCap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaChiTietTB;
    private javax.swing.JTextField txtTenThietBi;
    private javax.swing.JTextField txtThoiGianBH;
    // End of variables declaration//GEN-END:variables
}

class ImageFilter extends FileFilter {
    
    public final static String JPEG = "jpeg";
    public final static String JPG = "jpg";
    public final static String GIF = "gif";
    public final static String TIFF = "tiff";
    public final static String TIF = "tif";
    public final static String PNG = "png";
    
    @Override
    public boolean accept(File f) {
        if (f.isDirectory()) {
            return true;
        }
        
        String extension = getExtension(f);
        if (extension != null) {
            if (extension.equals(TIFF)
                    || extension.equals(TIF)
                    || extension.equals(GIF)
                    || extension.equals(JPEG)
                    || extension.equals(JPG)
                    || extension.equals(PNG)) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }
    
    @Override
    public String getDescription() {
        return "Image Only";
    }
    
    String getExtension(File f) {
        String ext = null;
        String s = f.getName();
        int i = s.lastIndexOf('.');
        
        if (i > 0 && i < s.length() - 1) {
            ext = s.substring(i + 1).toLowerCase();
        }
        return ext;
    }
}
