
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author skqist225
 */
public class AddSupplierForm extends javax.swing.JDialog {

    /**
     * Creates new form AddSupplier
     */
    public AddSupplierForm(java.awt.Frame parent, int index, boolean isUpdate, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Thêm nhà cung cấp");

        _sC = new SupplierController();
        _lS = _sC.getSuppliersInfo();
        _parent = parent;

        if (isUpdate && index >= 0) {
            this.setTitle("Cập nhật nhà cung cấp");
            fillOutInfo(index);
        } else {
            txtMaNCC.setText(_lS.get(_lS.size() - 1).getSupplierId() + 1 + "");
        }

        txtMaNCC.setEditable(false);
        txtMaNCC.setFocusable(false);
        txtTenNCC.requestFocus();

        initAlert();
    }

    public final void initAlert() {
        initAlertLabel(alertTNCC);
        initAlertLabel(alertDCNCC);
        initAlertLabel(alertSDTNCC);
    }

    public void fillOutInfo(int index) {
        Supplier s = _lS.get(index);

        txtMaNCC.setText(s.getSupplierId() + "");
        txtTenNCC.setText(s.getName());
        txtDiaChiNCC.setText(s.getAddress());
        txtSDT.setText(s.getPhoneNumber());

        btnConfirm.setText("Cập nhật");
    }

    public void initAlertLabel(JLabel label) {
        label.setText("");
        label.setSize(0, 0);
    }

    public void createAlert(JLabel label, String alertContent) {
        label.setSize(alertContent.length(), 17);
        label.setText(alertContent);
        label.setVisible(true);
    }

    public void resetField() {
        txtTenNCC.setText("");
        txtDiaChiNCC.setText("");
        txtSDT.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        txtTenNCC = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChiNCC = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        alertTNCC = new javax.swing.JLabel();
        alertDCNCC = new javax.swing.JLabel();
        alertSDTNCC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setLabelFor(txtMaNCC);
        jLabel1.setText("Mã nhà cung cấp:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Tên nhà cung cấp:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Địa chỉ nhà cung cấp:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");

        txtTenNCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenNCCKeyReleased(evt);
            }
        });

        txtSDT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSDTKeyReleased(evt);
            }
        });

        txtDiaChiNCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiaChiNCCKeyReleased(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(51, 153, 0));
        btnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btnConfirm.setText("Thêm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.png"))); // NOI18N
        jButton2.setText("Hủy bỏ");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        jButton3.setText("Làm mới");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("THÊM NHÀ CUNG CẤP");

        alertTNCC.setForeground(new java.awt.Color(255, 0, 0));
        alertTNCC.setText("Tên NCC alert");

        alertDCNCC.setForeground(new java.awt.Color(255, 0, 0));
        alertDCNCC.setText("Địa chỉ NCC alert");

        alertSDTNCC.setForeground(new java.awt.Color(255, 0, 0));
        alertSDTNCC.setText("SDT NCC alert");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel5)))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alertSDTNCC)
                            .addComponent(txtDiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alertTNCC)
                            .addComponent(alertDCNCC))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertDCNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertSDTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnConfirm)
                    .addComponent(jButton2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        initAlert();
        String maNCCs = txtMaNCC.getText();
        String tenNCC = txtTenNCC.getText();
        String diaChiNCC = txtDiaChiNCC.getText();
        String sdtNCC = txtSDT.getText();
        boolean check = true;

        if (tenNCC.length() == 0) {
            createAlert(alertTNCC, "Tên không được để trống");
            check = false;
        }
        if (diaChiNCC.equals("")) {
            createAlert(alertDCNCC, "Địa chỉ không được để trống");
            check = false;
        }

        if (tenNCC.length() < 0 || tenNCC.matches("[^a-zA-Z]+")) {
            createAlert(alertTNCC, "Tên NCC phải là chữ cái");
            check = false;
        }
        if (!sdtNCC.matches("^[0]{1}[0-9]{9}$") || sdtNCC.length() < 0) {
            createAlert(alertSDTNCC, "SDT không hợp lệ (10 chữ số)");
            check = false;
        }

        if (check) {
            int maNCC = Integer.parseInt(maNCCs);
            Supplier s = new Supplier(maNCC, tenNCC, diaChiNCC, sdtNCC);
            if (_sC.isIdExist(maNCC)) {
                if (_sC.updateSupplier(s)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    AdminDashBoard admDb = (AdminDashBoard) _parent;
                    admDb.loadDatabase();
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }
            } else {
                if (_sC.addNewSupplier(s)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    AdminDashBoard admDb = (AdminDashBoard) _parent;
                    admDb.loadDatabase();
                    admDb.getSupplierList();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }
            }
            resetField();
            this.dispose();
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        resetField();
        initAlert();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtTenNCCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenNCCKeyReleased
        String tenNCC = txtTenNCC.getText();
        if (tenNCC.matches("[a-zA-Z]+")) {
            initAlertLabel(alertTNCC);
        }
    }//GEN-LAST:event_txtTenNCCKeyReleased

    private void txtDiaChiNCCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiNCCKeyReleased
        String diaChiNCC = txtDiaChiNCC.getText();
        if (diaChiNCC.length() > 0) {
            initAlertLabel(alertDCNCC);
        }
    }//GEN-LAST:event_txtDiaChiNCCKeyReleased

    private void txtSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyReleased
        String sdtNCC = txtSDT.getText();
        if (sdtNCC.matches("^[0-9]{10}$")) {
            initAlertLabel(alertSDTNCC);
        }
    }//GEN-LAST:event_txtSDTKeyReleased

    private SupplierController _sC = null;
    private List<Supplier> _lS;
    private java.awt.Frame _parent;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertDCNCC;
    private javax.swing.JLabel alertSDTNCC;
    private javax.swing.JLabel alertTNCC;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDiaChiNCC;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables
}
