
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nguyen Hai Dang
 */
public class ImportForm extends javax.swing.JFrame {

    /**
     * Creates new form ImportForm
     */
    public ImportForm(int userID) {
        _userID = userID;
        
        initComponents();
        initRenderer();
    }
    
    public void addEquiment(String id, String name, String status, int price, String picture, String detailID)
    {
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        Vector vector = new Vector();
        vector.add(id);
        vector.add(name);
        vector.add(status);
        vector.add(price);
        vector.add(picture);
        vector.add(detailID);
        tableModel.addRow(vector);
        
        checkIDList.add(id.substring(0, 3));
    }
    
    private void saveEquipmentToDatabase(String id, String status, int price, String detailID, int importID, java.sql.Timestamp timeStamp)
    {
        Connection connector = ConnectMysql.getConnectDB();
        String sql = "insert into gym_equipments values (?,?,?,?,?,?,?)";
        try {
            PreparedStatement ps = connector.prepareStatement(sql);
            ps.setString(1, id);
            ps.setString(2, status);
            ps.setInt(3, price);
            ps.setString(4, detailID);
            ps.setInt(5, importID);
            ps.setTimestamp(6, timeStamp);
            ps.setTimestamp(7, timeStamp);
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(ImportForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void saveImportDetailToDatabase(int importID, int userID, java.sql.Date date)
    {
        Connection connector = ConnectMysql.getConnectDB();
        String sql = "insert into import_details values (?,?,?)";
        try {
            PreparedStatement ps = connector.prepareStatement(sql);
            ps.setInt(1, importID);
            ps.setInt(2, userID);
            ps.setDate(3, date);
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(ImportForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void initRenderer()
    {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        loadImportID();
        loadUserName();
        importDateTextField.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
    }
    
    private void loadUserName()
    {
        Connection connector = ConnectMysql.getConnectDB();
        String sql = "select * from users where id = '"+_userID+"'";
        String userName = "";
        try {
            ResultSet rs = connector.createStatement().executeQuery(sql);
            if(rs.next())
            {
                userName = rs.getString("lastName") + " " + rs.getString("firstName");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ImportForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        userNameTextField.setText(userName);
    }
    
    private void loadImportID()
    {
        Connection connector = ConnectMysql.getConnectDB();
        String sql = "select count(id) as countID from import_details";
        int id = 1;
        try {
            ResultSet rs = connector.createStatement().executeQuery(sql);
            if(rs.next())
            {
                id = rs.getInt("countID")+1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ImportForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        importIDTextField.setText(id+"");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importIDLabel = new javax.swing.JLabel();
        importIDTextField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        importDateLabel = new javax.swing.JLabel();
        importDateTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        importIDLabel.setText("Mã phiếu nhập");

        importIDTextField.setEditable(false);

        userNameLabel.setText("Tên nhân viên");

        userNameTextField.setEditable(false);

        addButton.setText("Thêm thiết bị");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thiết bị", "Tên thiết bị", "Trạng thái", "Giá", "Hình ảnh", "Mã loại thiết bị"
            }
        ));
        scrollPane.setViewportView(table);

        saveButton.setText("Lưu");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Hủy");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        importDateLabel.setText("Ngày nhập");

        importDateTextField.setEditable(false);

        jButton1.setText("Sửa");
        jButton1.setEnabled(false);

        jButton2.setText("Xóa");
        jButton2.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(importIDLabel)
                            .addComponent(userNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(importIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(userNameTextField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(importDateLabel)
                                .addGap(17, 17, 17)
                                .addComponent(importDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importIDLabel)
                    .addComponent(importIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton)
                    .addComponent(importDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importDateLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String id, status, detailID;
        int price;
        java.sql.Timestamp timeStamp = new java.sql.Timestamp(new Date().getTime());
        java.sql.Date date = new java.sql.Date(new Date().getTime());
        int importID = Integer.valueOf(importIDTextField.getText());
        
        if(table.getRowCount()>0)
        {
            saveImportDetailToDatabase(importID,_userID,date);
        
            for(int i=0; i<table.getRowCount(); i++)
            {
                id = table.getValueAt(i, 0).toString();
                status = table.getValueAt(i, 2).toString();
                price = Integer.valueOf(table.getValueAt(i, 3).toString());
                detailID = table.getValueAt(i, 5).toString();
                saveEquipmentToDatabase(id, status, price, detailID, importID, timeStamp);
            }
            System.out.println("Lưu vào CSDL thành công");
        }
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        javax.swing.JFrame addEquimentForm = new AddEquimentForm(this);
        addEquimentForm.setVisible(true);
        addEquimentForm.setLocationRelativeTo(this);
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private int _userID = 0;
    public Vector<String> checkIDList = new Vector<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel importDateLabel;
    private javax.swing.JTextField importDateTextField;
    private javax.swing.JLabel importIDLabel;
    private javax.swing.JTextField importIDTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton saveButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
