import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
public class SettingFrom extends javax.swing.JFrame {

    private int userId;

    private String userQuery() {
        return "SELECT * FROM `users` WHERE id = " + userId;
    }

    /**
     * Creates new form SettingFrom
     */
    public SettingFrom(int userId) {
        this.userId = userId;
        initComponents();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
                exitCallBack.exit();
            }
        });
        initUserInfo();
    }

    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

    private void initUserInfo() {
        Connection connectDB = ConnectMysql.getConnectDB();
        try {
            ResultSet rs = connectDB.createStatement().executeQuery(userQuery());
            rs.next();
            fullNameLb.setText(rs.getString("firstName") + " " + rs.getString("lastName"));
            birthDayLb.setText(format.format(rs.getDate("birthDay")));
            emailLb.setText(rs.getString("email"));
            contactLb.setText(rs.getString("contactNumber"));
            createLb.setText(format.format(rs.getDate("created_at")));
            updateLb.setText(format.format(rs.getDate("updated_at")));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logOutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fullNameLb = new javax.swing.JLabel();
        birthDayLb = new javax.swing.JLabel();
        emailLb = new javax.swing.JLabel();
        contactLb = new javax.swing.JLabel();
        createLb = new javax.swing.JLabel();
        updateLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        logOutBtn.setText("Logout");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên:");

        jLabel2.setText("Ngày sinh:");

        jLabel3.setText("Email:");

        jLabel4.setText("Số điện thoại:");

        jLabel5.setText("Ngày tạo:");

        jLabel6.setText("Ngày cập nhật:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullNameLb)
                    .addComponent(birthDayLb)
                    .addComponent(emailLb)
                    .addComponent(contactLb)
                    .addComponent(createLb)
                    .addComponent(updateLb))
                .addContainerGap(306, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logOutBtn)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fullNameLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(birthDayLb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contactLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(createLb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(updateLb))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        logOutCallBack.logout();
        dispose();
        LoginForm.create();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private ExitCallBack exitCallBack;

    public void setExitCallBack(ExitCallBack exitCallBack) {
        this.exitCallBack = exitCallBack;
    }

    public interface ExitCallBack {

        void exit();
    }
    private LogOutCallBack logOutCallBack = null;

    public void setLogOutCallBack(LogOutCallBack logOutCallBack) {
        this.logOutCallBack = logOutCallBack;
    }

    public interface LogOutCallBack {

        void logout();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthDayLb;
    private javax.swing.JLabel contactLb;
    private javax.swing.JLabel createLb;
    private javax.swing.JLabel emailLb;
    private javax.swing.JLabel fullNameLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel updateLb;
    // End of variables declaration//GEN-END:variables
}
