
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
public class SettingFrom extends javax.swing.JFrame implements CreateLoginInfoForm.ExitCallBack, CreateUserForm.ExitCallBack {

    /**
     * Creates new form SettingFrom
     */
    public SettingFrom(int _userId) {
        this._userId = _userId;
        initComponents();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
                _exitCallBack.exit();
            }
        });
        initUserInfo();
    }

    public void setLogOutCallBack(LogOutCallBack _logOutCallBack) {
        this._logOutCallBack = _logOutCallBack;
    }

    @Override
    public void exit() {
        setEnabled(true);
        setVisible(true);
    }

    public interface LogOutCallBack {

        void logout();
    }

    public void setExitCallBack(ExitCallBack _exitCallBack) {
        this._exitCallBack = _exitCallBack;
    }

    public interface ExitCallBack {

        void exit();
    }

    private void initUserInfo() {
        Connection connectDB = ConnectMysql.getConnectDB();
        try {
            ResultSet rs = connectDB.createStatement().executeQuery(userQuery());
            rs.next();
            fullNameLb.setText(rs.getString("firstName") + " " + rs.getString("lastName"));
            birthDayLb.setText(_format.format(rs.getDate("birthDay")));
            emailLb.setText(rs.getString("email"));
            contactLb.setText(rs.getString("contactNumber"));
            createLb.setText(_format.format(rs.getDate("created_at")));
            updateLb.setText(_format.format(rs.getDate("updated_at")));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private String userQuery() {
        return "SELECT * FROM `users` WHERE id = " + _userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logOutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fullNameLb = new javax.swing.JLabel();
        birthDayLb = new javax.swing.JLabel();
        emailLb = new javax.swing.JLabel();
        contactLb = new javax.swing.JLabel();
        createLb = new javax.swing.JLabel();
        updateLb = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createUserBtn = new javax.swing.JButton();
        createLoginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        logOutBtn.setText("Đăng xuất");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên:");

        jLabel2.setText("Ngày sinh:");

        jLabel3.setText("Email:");

        jLabel4.setText("Số điện thoại:");

        jLabel5.setText("Ngày tạo:");

        jLabel6.setText("Ngày cập nhật:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("CÀI ĐẶT");

        createUserBtn.setText("Create user");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        createLoginBtn.setText("Create login");
        createLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fullNameLb)
                                    .addComponent(birthDayLb)
                                    .addComponent(emailLb)
                                    .addComponent(contactLb)
                                    .addComponent(createLb)
                                    .addComponent(updateLb)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logOutBtn)
                        .addGap(18, 18, 18)
                        .addComponent(createUserBtn)
                        .addGap(18, 18, 18)
                        .addComponent(createLoginBtn)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fullNameLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(birthDayLb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contactLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(createLb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(updateLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOutBtn)
                    .addComponent(createUserBtn)
                    .addComponent(createLoginBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        _logOutCallBack.logout();
        dispose();
        LoginForm.create();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        CreateUserForm createUserForm = new CreateUserForm();
        createUserForm.setLocationRelativeTo(null);
        createUserForm.setVisible(true);
        createUserForm.setExitCallBack(this);
        setEnabled(false);
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void createLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLoginBtnActionPerformed
        CreateLoginInfoForm createLoginInfoForm = new CreateLoginInfoForm();
        createLoginInfoForm.setLocationRelativeTo(null);
        createLoginInfoForm.setVisible(true);
        createLoginInfoForm.setExitCallBack(this);
        setEnabled(false);
    }//GEN-LAST:event_createLoginBtnActionPerformed

    private SimpleDateFormat _format = new SimpleDateFormat("dd/MM/yyyy");
    private LogOutCallBack _logOutCallBack = null;
    private ExitCallBack _exitCallBack;
    private int _userId;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthDayLb;
    private javax.swing.JLabel contactLb;
    private javax.swing.JLabel createLb;
    private javax.swing.JButton createLoginBtn;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JLabel emailLb;
    private javax.swing.JLabel fullNameLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel updateLb;
    // End of variables declaration//GEN-END:variables
}
